### ISSUE TITLE
gazebo

### ISSUE THREAD

**Issue by xujiajie1997** [nubot-nudt/dynamic_task_allocation#10]
What is the cause of this problem and how to solve it，thanks a lot
![2022-01-12 15-52-59屏幕截图](https://user-images.githubusercontent.com/73786620/149086400-81d51853-3a69-4479-a8bf-94c0930e42d6.png)
t

**Comment by xujiajie1997** [comment]
车在原地不动

**Comment by zhaoziyie** [comment]
我的也是，请问有解决方法马？

**Comment by xujiajie1997** [comment]
还没解决 不知道为什么

**Comment by zhaoziyie** [comment]
try 16.04? is ok?

**Comment by xujiajie1997** [comment]
我下载的是18.04

**Comment by nubot-nudt** [comment]
通过您的截图发现，spawn_robots.sh并没有找到，所以负责任务分配算法的节点”/task_allocation_node“并没有启动，导致机器人不动，你可以通过rosnode list查看当前已运行的节点，也可以尝试手动启动：”rosrun task_allocation  task_allocation_node Robot${j}  __name:=Robot${j}_task_allocation“。

You can see from your screenshot that ”spawn_robots.sh“ is not found, so the node "/task_allocation_node", which is responsible for the task allocation algorithm, is not started, which causes the robot not to move, you can check the currently running nodes through the "rosnode list". You can also try to start it manually, 
`rosrun task_allocation task_allocation_node Robot${j} __name:=Robot${j}_task_allocation`

**Comment by xujiajie1997** [comment]
问题成功解决了 谢谢！请问如果后面发论文想使用下您的动态任务分配系统，可以引用您的文章并使用吗

**Comment by nubot-nudt** [comment]
可以,欢迎使用!

**Comment by xujiajie1997** [comment]
谢谢！
