### ISSUE TITLE
点击start后,所有机器人都不移动,显示为IDLE状态

### ISSUE THREAD

**Issue by wanghuohuo0716** [nubot-nudt/dynamic_task_allocation#5]
非常感谢您开源此项目!

我在运行这个程序时,发现机器人好像无法移动

操作:我按照您视频步骤顺序,1.选择机器人 2.载入地图 3.start.
结果:机器人状态的显示时IDLE状态
![image](https://user-images.githubusercontent.com/20619811/63779081-876d5c00-c918-11e9-888a-d1f515895798.png)

**Comment by wanghuohuo0716** [comment]
[
![image](https://user-images.githubusercontent.com/20619811/63779209-c13e6280-c918-11e9-8398-805a584e82fb.png)
](url)

**Comment by wanghuohuo0716** [comment]
终端显示内容

[ INFO] [1566956327.339373366, 32.625000000]: Spwan robots
sh: 1: ../../../src/allocation_common/spawn_robots.sh: not found

**Comment by wanghuohuo0716** [comment]
![image](https://user-images.githubusercontent.com/20619811/63820883-8ae6fe80-c97d-11e9-9ccc-ac0a74fb91d2.png)

**Comment by wanghuohuo0716** [comment]
在整个包重新使用catkin_make -j1编译后,再执行source devel/setup.sh,发现无法source.

错误提示:
Missing Python script: /home/wanghuohuo/catkin_ws/dynamic_task_allocation/devel/_setup_util.py

但是在dynamic_task_allocation/devel文件夹中存在此文件_setup_util.py.

猜测可能是这个原因导致机器人无法运动的

**Comment by nubot-nudt** [comment]
你好，根据你目前的现象，我觉得大概的原因是工程的路径问题，就是文件实际存在但却不能正常索引。首先机器人不能动正是因为找不到spawn_robots.sh，这个脚本是用来根据你当前选择的机器人数量载入机器人节点的，从ros_graph中确实没看到机器人节点。所以gazebo中有的只是模型没有程序，无法正常移动。关于你运行python3 train.py报的错误也是一样的，问题出在找不到跟ros相关的一系列包（rospy, roslib...)，你可以尝试在终端中再手动source /opt/ros/kinetic/setup.bash。由于我没有遇到过类似的问题，所以没法给出绝对的解决方案，不好意思。

**Comment by wanghuohuo0716** [comment]
非常感谢您的回复，我会再尝试下！如果有了结果，我会第一时间在issue上回复的！

________________________________
发件人: nubot <notifications@github.com>
发送时间: Wednesday, August 28, 2019 5:40:35 PM
收件人: nubot-nudt/dynamic_task_allocation <dynamic_task_allocation@noreply.github.com>
抄送: Yan Wang <wanghuohuo0716@outlook.com>; Author <author@noreply.github.com>
主题: Re: [nubot-nudt/dynamic_task_allocation] 点击start后,所有机器人都不移动,显示为IDLE状态 (#5)


你好，根据你目前的现象，我觉得大概的原因是工程的路径问题，就是文件实际存在但却不能正常索引。首先机器人不能动正是因为找不到spawn_robots.sh，这个脚本是用来根据你当前选择的机器人数量载入机器人节点的，从ros_graph中确实没看到机器人节点。所以gazebo中有的只是模型没有程序，无法正常移动。关于你运行python3 train.py报的错误也是一样的，问题出在找不到跟ros相关的一系列包（rospy, roslib...)，你可以尝试在终端中再手动source /opt/ros/kinetic/setup.bash。由于我没有遇到过类似的问题，所以没法给出绝对的解决方案，不好意思。

―

**Comment by wanghuohuo0716** [comment]
确实是路径的问题,因为这个package所处的文件目录不一样,在~/catkin_ws/src/dynamic_task_allocation/src/control_terminal/src/maindialog.cpp
中在94行,把调用脚本的相对路径改为绝对路径即可.
